### ISSUE TITLE
Segfault after install

### ISSUE THREAD

**Issue by ldibanyez** [schnorr/viva#1]
Hi, 

I installed viva following the instructions in the wiki. PajeNG is well installed (I checked with the pj_dump and pajeng binaries), but when trying to run:
$> ./opt/viva/bin/viva 
or
$> ./opt/viva/bin/viva trc.trace
or
$> ./opt/viva/bin/viva --help
There is a segmentation fault.

My box is an ubuntu 12.04, I have the latest versions for this of all the dependencies

**Comment by schnorr** [comment]
Hi,

Sorry for the delay.

The latest version of Viva expects two parameters: the first one is the trace filename, the second is the graph configuration that viva needs to map trace entities to the graph representation. I could give you a better answer if you are able to provide me the file trc.trace and explain me what kind of graph you need: if it is based on the network topology, or it is purely an application graph.

Best,
Lucas

**Comment by mickours** [comment]
It is still a problem now on ubuntu or archlinux. I run the lastest git version with this command given by Arnaud but it segfault with this error. He said that you already have the trace and plist files.

```
./viva g5k_2ap_1Kt-2Kt_1E12_1E6-1E5.plist g5k_2ap_1Kt-2Kt_1E12_1E6-1E5_gray.trace
quality set to 0, viewZone calculated to 1,000000
[1]    25039 segmentation fault (core dumped)  ./viva g5k_2ap_1Kt-2Kt_1E12_1E6-1E5.plist
```

Thanks in advance,

Michael Mercier

_EDIT_: Ok it work when I reverse the arguments. maybe some arguments checks are needed

**Comment by schnorr** [comment]
Argument checking is now provided (456b94e), see man viva if you enable VIVA_DOC in cmake, or pass --help to the viva executable.
