### ISSUE TITLE
libvivautils doesn't have a SONAME/SOVERSION

### ISSUE THREAD

**Issue by lnussbaum** [schnorr/viva#2]
Hi,

viva currently installs a libvivautils library to /usr/lib/.

It should either be turned into a private library (moved to e.g. /usr/lib/viva), or be maintained as a proper shared library.

For the Debian package, I've added a SOVERSION, reusing code from pajeng.

**Comment by schnorr** [comment]
This issue has disappeared with commit f5facec.
