### ISSUE TITLE
Could you please release a new version?

### ISSUE THREAD

**Issue by mquinson** [schnorr/viva#5]
The tag viva-1.0 was set in 2013, and quite a lot of work was done since then. Could you please release a new version that I could package?

Thanks

**Comment by schnorr** [comment]
Done, I have added a new manpage for vv_treemap. Viva comprises two tools: viva (graph viz) and vv_treemap (treemap viz) for paje trace files.

**Comment by mquinson** [comment]
Thanks a lot
