### ISSUE TITLE
Build failure with gcc5 (due to boost?)

### ISSUE THREAD

**Issue by mquinson** [schnorr/viva#6]
Hello,

we have a bug in Debian: boost and MOC of Qt4 and boost do not play well together:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794704

I tried several solutions to fix it, all in vain. Maybe you will be more efficient that me?

**Comment by mquinson** [comment]
This issue was reported a second time against the Debian package (as bug=827349), but this time it is a "serious" issue (as it should according to the Debian policy). It means that if it not addressed very soon, the package will be removed from Testing.

I will give a try to the workaround presented in https://bugreports.qt.io/browse/QTBUG-22829 (reported in the first Debian bug), but if it does not work, I will really need your help here.

Thanks for this nice software,

**Comment by mquinson** [comment]
hello,

because of this bug, viva will be kicked out of Debian's testing very soon.

**Comment by schnorr** [comment]
I am installing gcc 5 to tackle this issue. What do you mean by "very soon"?

**Comment by mquinson** [comment]
Everything is on this page: https://packages.qa.debian.org/v/viva.html

**Comment by mquinson** [comment]
This seems to be fixed by the following patch (against pajeng), that you may want to integrate. 
https://anonscm.debian.org/cgit/collab-maint/pajeng.git/tree/debian/patches/no-boost-moc-ftbfs

**Comment by schnorr** [comment]
Hi, I just applied the patch to the Paje sources (the tag 1.3.2 contains the patched files). I have been compiling viva and pajeng using gcc version 5.4.0 20160609 (Debian 5.4.0-6) and compilation is working fine. Can you try again? Thanks. Feel free to reopen this issue if not resolved.
