### ISSUE TITLE
Where is the PajeThreadReader.h?

### ISSUE THREAD

**Issue by youareanidiot** [schnorr/viva#8]
Hi

The error "src/vv_treemap/VTApplication.h:21:30: fatal error: PajeThreadReader.h: No such file or directory" occurred. How to resolve it?

**Comment by schnorr** [comment]
Hi, which version of viva are you using? I have just cloned the repository and compiled it cleanly. I'm in the commit 1a3d1f680f06df87839af44d6ce8f33499772612 (the master branch). Can you confirm that you are using the latest version? If not, I suggest you to update.

**Comment by youareanidiot** [comment]
Thanks, I have solved the problem with copying PajeThreadReader.h from the package pajeng to /home/para/DAG/simgrid/SimGrid-3.13/viva/src/vv_treemap/

**Comment by mquinson** [comment]
I just stumbled upon the same bug while trying to recompile the debian package. Could you please release a new version if the git is fixing this issue? Thx,

**Comment by taniamalik** [comment]
Hi!
During make I am getting this error.
/home/tania/viva/src/viva/VivaApplication.cc:2:30: fatal error: PajeThreadReader.h: No such file or directory
 #include "PajeThreadReader.h"

Can you please help me how I can solve it? 
Thanks

**Comment by schnorr** [comment]
Hi,

PajeThreadReader is part of pajeng, a tool that viva relies on. To get it, please check http://github.com/schnorr/pajeng Make sure to configure cmake to set PAJE_UTILS_LIBRARY to ON. Then, install pajeng somewhere. Finally, configure viva (with cmake) to search your pajeng installation. You can do that by typing:

cmake -DPAJENG_PATH:PATH=$HOME/install/pajeng9/ ..

Let me know if that works for you.

**Comment by taniamalik** [comment]
Hi Lucas
I think the problem is in pajeng installation. It installation doesn't include PajeThreadReader.h file.
That is what I got when I installed it.
Install the project...
-- Install configuration: "Release"
-- Installing: /home/tania/bin/pj_gantt
-- Installing: /home/tania/lib/libpaje.so.1.3
-- Up-to-date: /home/tania/lib/libpaje.so.2
-- Up-to-date: /home/tania/lib/libpaje.so
-- Installing: /home/tania/include/PajeColor.h
-- Installing: /home/tania/include/PajeException.h
-- Installing: /home/tania/include/PajeProtocols.h
-- Installing: /home/tania/include/PajeComponent.h
-- Installing: /home/tania/include/PajeContainer.h
-- Installing: /home/tania/include/PajeData.h
-- Installing: /home/tania/include/PajeEntity.h
-- Installing: /home/tania/include/PajeEventDecoder.h
-- Installing: /home/tania/include/PajeEventDefinition.h
-- Installing: /home/tania/include/PajeTraceEvent.h
-- Installing: /home/tania/include/PajeEvent.h
-- Installing: /home/tania/include/PajeFileReader.h
-- Installing: /home/tania/include/PajeObject.h
-- Installing: /home/tania/include/PajeSimulator.h
-- Installing: /home/tania/include/PajeProbabilisticSimulator.h
-- Installing: /home/tania/include/PajeType.h
-- Installing: /home/tania/include/PajeValue.h
-- Installing: /home/tania/include/PajeDefinitions.h
-- Installing: /home/tania/include/PajeFlexReader.h
-- Installing: /home/tania/include/PajeUnity.h
-- Installing: /home/tania/include/PajeEnum.h
-- Installing: /home/tania/lib/pkgconfig/libpaje.pc
-- Installing: /home/tania/bin/pj_dump
-- Installing: /home/tania/bin/pj_equals

Might be the name of file changed?

**Comment by mquinson** [comment]
I think that this is a problem for the debian package, too.
Viva seem to depend on that file, so the Viva package is not buildable now that we disabled this the libpajeutils-dev package...
Any idea on how to solve this?
Thanks, Mt

**Comment by schnorr** [comment]
Sure, I think the best way to go is to come back with libpajeutils compilation option. I've just did this. Now, when you install pajeng you will have PajeThreadReader.h back. Here are the contents after an installation:

-- Up-to-date: /tmp/local/bin/pj_gantt
-- Up-to-date: /tmp/local/lib/libpaje.so.2.0
-- Up-to-date: /tmp/local/lib/libpaje.so.2
-- Up-to-date: /tmp/local/lib/libpaje.so
-- Up-to-date: /tmp/local/include/PajeColor.h
-- Up-to-date: /tmp/local/include/PajeException.h
-- Up-to-date: /tmp/local/include/PajeProtocols.h
-- Up-to-date: /tmp/local/include/PajeComponent.h
-- Up-to-date: /tmp/local/include/PajeContainer.h
-- Up-to-date: /tmp/local/include/PajeData.h
-- Up-to-date: /tmp/local/include/PajeEntity.h
-- Up-to-date: /tmp/local/include/PajeEventDecoder.h
-- Up-to-date: /tmp/local/include/PajeEventDefinition.h
-- Up-to-date: /tmp/local/include/PajeTraceEvent.h
-- Up-to-date: /tmp/local/include/PajeEvent.h
-- Up-to-date: /tmp/local/include/PajeFileReader.h
-- Up-to-date: /tmp/local/include/PajeObject.h
-- Up-to-date: /tmp/local/include/PajeSimulator.h
-- Up-to-date: /tmp/local/include/PajeProbabilisticSimulator.h
-- Up-to-date: /tmp/local/include/PajeType.h
-- Up-to-date: /tmp/local/include/PajeValue.h
-- Up-to-date: /tmp/local/include/PajeDefinitions.h
-- Up-to-date: /tmp/local/include/PajeFlexReader.h
-- Up-to-date: /tmp/local/include/PajeUnity.h
-- Up-to-date: /tmp/local/include/PajeEnum.h
-- Up-to-date: /tmp/local/lib/pkgconfig/libpaje.pc
-- Installing: /tmp/local/bin/pj_dump
-- Installing: /tmp/local/bin/pj_equals
-- Up-to-date: /tmp/local/lib/libpajeutils.so.1.3
-- Up-to-date: /tmp/local/lib/libpajeutils.so.2
-- Up-to-date: /tmp/local/lib/libpajeutils.so
-- Up-to-date: /tmp/local/include/PajeThreadReader.h
-- Up-to-date: /tmp/local/lib/pkgconfig/libpajeutils.pc
-- Installing: /tmp/local/man/man1/pj_equals.1
-- Installing: /tmp/local/man/man1/pj_dump.1

**Comment by schnorr** [comment]
Can you try again to see if the recent changes in pajeng fix the viva problem?

**Comment by taniamalik** [comment]
I tried!! it add some lib files but not the PajeThreadReader.h
The installation now includes:
-- Install configuration: "Release"
-- Installing: /home/tania/bin/pj_gantt
-- Installing: /home/tania/lib/libpaje.so.1.3
-- Up-to-date: /home/tania/lib/libpaje.so.2
-- Up-to-date: /home/tania/lib/libpaje.so
-- Installing: /home/tania/include/PajeColor.h
-- Installing: /home/tania/include/PajeException.h
-- Installing: /home/tania/include/PajeProtocols.h
-- Installing: /home/tania/include/PajeComponent.h
-- Installing: /home/tania/include/PajeContainer.h
-- Installing: /home/tania/include/PajeData.h
-- Installing: /home/tania/include/PajeEntity.h
-- Installing: /home/tania/include/PajeEventDecoder.h
-- Installing: /home/tania/include/PajeEventDefinition.h
-- Installing: /home/tania/include/PajeTraceEvent.h
-- Installing: /home/tania/include/PajeEvent.h
-- Installing: /home/tania/include/PajeFileReader.h
-- Installing: /home/tania/include/PajeObject.h
-- Installing: /home/tania/include/PajeSimulator.h
-- Installing: /home/tania/include/PajeProbabilisticSimulator.h
-- Installing: /home/tania/include/PajeType.h
-- Installing: /home/tania/include/PajeValue.h
-- Installing: /home/tania/include/PajeDefinitions.h
-- Installing: /home/tania/include/PajeFlexReader.h
-- Installing: /home/tania/include/PajeUnity.h
-- Installing: /home/tania/include/PajeEnum.h
-- Installing: /home/tania/lib/pkgconfig/libpaje.pc
-- Installing: /home/tania/bin/pj_dump
-- Installing: /home/tania/bin/pj_equals
-- Installing: /home/tania/lib/libpajeutils.so.1.3
-- Installing: /home/tania/lib/libpajeutils.so.2
-- Installing: /home/tania/lib/libpajeutils.so

**Comment by schnorr** [comment]
After updating to the latest master branch, can you create a new build directory and run cmake again? Or remove the CMakeCache.txt file and re-execute cmake again?

**Comment by taniamalik** [comment]
I removed the whole directory and got the same thing again. I checked your installation result it shows
-- Up-to-date: /tmp/local/include/PajeThreadReader.h
so its mean it is already there in your system. it won't install after adding libpajeutils.

**Comment by schnorr** [comment]
Hey, I'm not sure what you mean. I have just cleaned up the target installation directory, here's an extract of make install:
-- Installing: /tmp/local/include/PajeEnum.h
-- Installing: /tmp/local/lib/pkgconfig/libpaje.pc
-- Installing: /tmp/local/bin/pj_dump
-- Installing: /tmp/local/bin/pj_equals
-- Installing: /tmp/local/lib/libpajeutils.so.1.3
-- Installing: /tmp/local/lib/libpajeutils.so.2
-- Installing: /tmp/local/lib/libpajeutils.so
-- Removed runtime path from "/tmp/local/lib/libpajeutils.so.1.3"
-- Installing: /tmp/local/include/PajeThreadReader.h
-- Installing: /tmp/local/lib/pkgconfig/libpajeutils.pc
-- Installing: /tmp/local/man/man1/pj_gantt.1
-- Installing: /tmp/local/man/man1/pj_equals.1
-- Installing: /tmp/local/man/man1/pj_dump.1

As you can see, with the master branch right now PajeThreadReader.h gets installed. There is no problem compiling viva against such pajeng installation. Best.
