### ISSUE TITLE
Compilation Error: VTApplication.cc:43  uses PajeSimulator, but its out of date.

### ISSUE THREAD

**Issue by slambrisca** [schnorr/viva#9]
When trying to compile VIVA got this error:

> no matching function for call to ‘PajeSimulator::PajeSimulator(double&, int&)’

Looking into the VIVA and PAJENG sources, found out that since this commit  [(https://github.com/schnorr/pajeng/commit/27fdfcef798f78b2ba22c0ed641d8c265f2dfefa)] PajeSimulator has not anymore a two parameters constructor, anyways VTApplication.cc is still using it with two parameters, at least on line 43:

`simulator = new PajeSimulator (args->stopat, args->ignoreIncompleteLinks);`

I guess it needs to be updated

**Comment by schnorr** [comment]
Hi, thanks for the bug report. It should be fixed with https://github.com/schnorr/pajeng/tree/827c3826eb12cebc7b4f7569be8aebff7a7a8796. Can you confirm?

**Comment by slambrisca** [comment]
It's fixed!
Thanks!
